name = "urae-edge"
main = "worker.js"
compatibility_date = "2024-01-01"

[alias]
env = "./env.js"

[assets]
directory = "./public"

[build]
command = "wasm-pack build --target web --out-dir public/pkg"
