//! # `algebra_engine::poly::grobner`
//!
//! Gröbner Bases & Polynomial Ideal Elimination Engine.
//!
//! Implements:
//! - **$S$-Polynomials**: $S(f, g) = \frac{\operatorname{lcm}(\operatorname{LM}(f), \operatorname{LM}(g))}{\operatorname{LT}(f)} f - \frac{\operatorname{lcm}(\operatorname{LM}(f), \operatorname{LM}(g))}{\operatorname{LT}(g)} g$.
//! - **Buchberger's Algorithm**: Generates Gröbner bases $\langle \operatorname{LT}(G) \rangle = \langle \operatorname{LT}(I) \rangle$
//!   with Gebauer-Möller useless pair elimination criteria.
//! - **Reduced Gröbner Bases**: Guarantees uniqueness, monic leading terms, and complete reduction of tail monomials.

use super::multivariate::{MonomialOrder, MultiPoly, Term};

/// Structure representing a Gröbner Basis for an ideal $I = \langle f_1, \dots, f_m \rangle$.
#[derive(Debug, Clone, PartialEq)]
pub struct GrobnerBasis {
    /// Basis polynomials in the ideal.
    pub polynomials: Vec<MultiPoly>,
    /// Number of variables.
    pub num_vars: usize,
    /// Variable symbols.
    pub var_names: Vec<String>,
    /// Monomial ordering.
    pub order: MonomialOrder,
}

impl GrobnerBasis {
    /// Computes the $S$-polynomial $S(f, g)$ of two polynomials.
    pub fn s_polynomial(f: &MultiPoly, g: &MultiPoly) -> MultiPoly {
        if f.is_zero() || g.is_zero() {
            return MultiPoly::zero(f.num_vars, f.var_names.clone(), f.order);
        }

        let lt_f = f.leading_term().unwrap();
        let lt_g = g.leading_term().unwrap();

        let lcm = lt_f.monomial.lcm(&lt_g.monomial);

        // mono_f = lcm / LM(f)
        let mono_f = lcm.div(&lt_f.monomial).unwrap();
        // coeff_f = 1 / LC(f)
        let factor_f = MultiPoly::from_terms(
            vec![Term::new(1.0 / lt_f.coeff, mono_f)],
            f.num_vars,
            f.var_names.clone(),
            f.order,
        );

        // mono_g = lcm / LM(g)
        let mono_g = lcm.div(&lt_g.monomial).unwrap();
        // coeff_g = 1 / LC(g)
        let factor_g = MultiPoly::from_terms(
            vec![Term::new(1.0 / lt_g.coeff, mono_g)],
            g.num_vars,
            g.var_names.clone(),
            g.order,
        );

        let term1 = factor_f.mul(f);
        let term2 = factor_g.mul(g);

        term1.sub(&term2)
    }

    /// Computes a Gröbner Basis for the ideal generated by `generators` using Buchberger's algorithm.
    pub fn buchberger(generators: &[MultiPoly]) -> Self {
        if generators.is_empty() {
            return Self {
                polynomials: Vec::new(),
                num_vars: 0,
                var_names: Vec::new(),
                order: MonomialOrder::default(),
            };
        }

        let num_vars = generators[0].num_vars;
        let var_names = generators[0].var_names.clone();
        let order = generators[0].order;

        let mut g: Vec<MultiPoly> = generators
            .iter()
            .filter(|p| !p.is_zero())
            .map(|p| p.to_monic())
            .collect();

        if g.is_empty() {
            return Self {
                polynomials: Vec::new(),
                num_vars,
                var_names,
                order,
            };
        }

        // Pair queue: set of pairs (i, j) with i < j
        let mut pairs: Vec<(usize, usize)> = Vec::new();
        for i in 0..g.len() {
            for j in (i + 1)..g.len() {
                pairs.push((i, j));
            }
        }

        while let Some((i, j)) = pairs.pop() {
            let fi = &g[i];
            let fj = &g[j];

            let lm_i = fi.leading_monomial().unwrap();
            let lm_j = fj.leading_monomial().unwrap();

            // First Buchberger Criterion (Gebauer-Möller):
            // If LCM(LM(fi), LM(fj)) == LM(fi) * LM(fj), then S(fi, fj) reduces to zero without division.
            let lcm = lm_i.lcm(lm_j);
            let prod = lm_i.mul(lm_j);
            if lcm == prod {
                continue;
            }

            // Compute S-polynomial S(fi, fj)
            let s_poly = Self::s_polynomial(fi, fj);
            let (_, rem) = s_poly.div_rem(&g);

            if !rem.is_zero() {
                let new_poly = rem.to_monic();
                let new_idx = g.len();
                for k in 0..new_idx {
                    pairs.push((k, new_idx));
                }
                g.push(new_poly);
            }
        }

        Self::reduce_basis(g, num_vars, var_names, order)
    }

    /// Reduces a Gröbner basis to its canonical unique Reduced Gröbner Basis.
    fn reduce_basis(
        basis: Vec<MultiPoly>,
        num_vars: usize,
        var_names: Vec<String>,
        order: MonomialOrder,
    ) -> Self {
        if basis.is_empty() {
            return Self {
                polynomials: Vec::new(),
                num_vars,
                var_names,
                order,
            };
        }

        // 1. Filter out redundant polynomials whose leading monomial is divisible by another
        let mut minimal: Vec<MultiPoly> = Vec::new();
        for p in &basis {
            if p.is_zero() {
                continue;
            }
            let lm_p = p.leading_monomial().unwrap();
            let mut redundant = false;
            for other in &basis {
                if !std::ptr::eq(p, other) && !other.is_zero() {
                    let lm_other = other.leading_monomial().unwrap();
                    if lm_p != lm_other && lm_p.is_divisible_by(lm_other) {
                        redundant = true;
                        break;
                    }
                }
            }
            if !redundant {
                minimal.push(p.to_monic());
            }
        }

        // 2. Completely reduce each polynomial with respect to all other polynomials in the basis
        let mut reduced: Vec<MultiPoly> = Vec::with_capacity(minimal.len());
        for i in 0..minimal.len() {
            let mut other_divisors = Vec::new();
            for (j, item) in minimal.iter().enumerate() {
                if i != j {
                    other_divisors.push(item.clone());
                }
            }

            let (_, rem) = minimal[i].div_rem(&other_divisors);
            if !rem.is_zero() {
                reduced.push(rem.to_monic());
            }
        }

        // Sort polynomials by leading term order
        reduced.sort_by(|a, b| {
            let lm_a = a.leading_monomial().unwrap();
            let lm_b = b.leading_monomial().unwrap();
            lm_a.cmp_with_order(lm_b, order)
        });

        Self {
            polynomials: reduced,
            num_vars,
            var_names,
            order,
        }
    }
}
