[package]
name = "urae-lsp"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Language Server Protocol (LSP) Engine for URAE Mathematical Scripting in VS Code, Neovim & Zed"

[lib]
test = false
doctest = false

[lints]
workspace = true

[dependencies]
urae = { workspace = true, features = ["full", "cli"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
mimalloc.workspace = true
